import './globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { cookies } from 'next/headers'

import { Toaster } from '@/components/toast'
import { Mode } from '@/types'
import { clx } from '@/utils/clx'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const cookie = cookies()
  const mode = cookie.get('mode')?.value as Mode

  return (
    <html lang="en" data-mode={mode}>
      <body className={clx(inter.className, 'select-none')}>
        {children}
        <Toaster theme={mode} />
      </body>
    </html>
  )
}
